plugins {
    id 'java'
    alias(libs.plugins.quarkus)
    alias(libs.plugins.jandex)
}

dependencies {
    implementation enforcedPlatform(libs.quarkus.bom)
    implementation libs.quarkus.logging.json
    implementation libs.jakarta.cdi.api
    implementation libs.jakarta.interceptor.api
    implementation libs.quarkus.rest
    implementation libs.quarkus.rest.client
    implementation libs.quarkus.rest.client.jackson
    implementation libs.quarkus.arc
    implementation libs.quarkus.smallrye.fault.tolerance
    implementation libs.quarkus.smallrye.health

    testImplementation libs.junit.jupiter
    testImplementation libs.assertj.core
    testRuntimeOnly libs.junit.platform.launcher
}
