quarkus.http.port=49254
quarkus.application.name=dresden
quarkus.rest-client.london-api.url=${LONDON_API_URL:http://localhost:49252}
quarkus.rest-client.firenze-api.url=${FIRENZE_API_URL:http://localhost:49253}
quarkus.rest-client.dresden-api.url=${DRESDEN_API_URL:http://localhost:49254}
