quarkus.http.port=49254
quarkus.application.name=dresden
o11y.app.initial-sequence.enabled=false

quarkus.log.level=INFO
quarkus.log.category."ch.nickl.o11y".level=DEBUG

quarkus.log.json.log-format=ecs
quarkus.log.json.fields.mdc.enabled=true
quarkus.log.json.fields.mdc.flat-fields=true
quarkus.log.json.additional-field."service.name".value=${quarkus.application.name}
quarkus.log.json.additional-field."service.version".value=${quarkus.application.version}

%dev.quarkus.log.json.console.enabled=false
%test.quarkus.log.json.console.enabled=false
quarkus.log.console.format=%d{HH:mm:ss.SSS} %-5p [%c{2.}] (%t) %X %s%e%n
quarkus.log.console.darken=1
