[versions]
quarkus = "3.39.1"
jandex = "2.3.0"
cdi-api = "4.1.0"
interceptor-api = "2.2.0"
logging-json = "3.5.0"
assertj = "3.27.3"

[libraries]
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "quarkus" }
quarkus-rest = { group = "io.quarkus", name = "quarkus-rest" }
quarkus-rest-client = { group = "io.quarkus", name = "quarkus-rest-client" }
quarkus-rest-client-jackson = { group = "io.quarkus", name = "quarkus-rest-client-jackson" }
quarkus-arc = { group = "io.quarkus", name = "quarkus-arc" }
quarkus-smallrye-fault-tolerance = { group = "io.quarkus", name = "quarkus-smallrye-fault-tolerance" }
quarkus-smallrye-health = { group = "io.quarkus", name = "quarkus-smallrye-health" }
jakarta-cdi-api = { group = "jakarta.enterprise", name = "jakarta.enterprise.cdi-api", version.ref = "cdi-api" }
jakarta-interceptor-api = { group = "jakarta.interceptor", name = "jakarta.interceptor-api", version.ref = "interceptor-api" }
quarkus-logging-json = { group = "io.quarkiverse.loggingjson", name = "quarkus-logging-json", version.ref = "logging-json" }
quarkus-junit5 = { group = "io.quarkus", name = "quarkus-junit5" }
rest-assured = { group = "io.rest-assured", name = "rest-assured" }
awaitility = { group = "org.awaitility", name = "awaitility" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
jandex = { id = "org.kordamp.gradle.jandex", version.ref = "jandex" }
