plugins {
    alias(libs.plugins.quarkus)
}

dependencies {
    implementation enforcedPlatform(libs.quarkus.bom)
    implementation libs.quarkus.logging.json
    implementation project(':o11y-app')
    implementation libs.quarkus.rest
    implementation libs.quarkus.rest.client.jackson
    implementation libs.quarkus.arc

    testImplementation libs.quarkus.junit5
    testImplementation libs.rest.assured
    testImplementation libs.assertj.core
    testImplementation libs.awaitility
    testImplementation libs.wiremock
    testRuntimeOnly libs.junit.platform.launcher
}
