# Default port for o11y-app, but can be overridden by subprojects
quarkus.http.port=49255
quarkus.application.name=o11y-app
o11y.app.delay=2s
o11y.app.hops=10
o11y.app.initial-sequence.enabled=true
quarkus.rest-client.london-api.url=${LONDON_API_URL:http://127.0.0.1:49252}
quarkus.rest-client.firenze-api.url=${FIRENZE_API_URL:http://127.0.0.1:49253}
quarkus.rest-client.dresden-api.url=${DRESDEN_API_URL:http://127.0.0.1:49254}
